# Generated by Django 4.2.5 on 2023-09-13 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mosque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Salah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fajr', models.CharField(max_length=50)),
                ('dhuhr', models.CharField(max_length=50)),
                ('asr', models.CharField(max_length=50)),
                ('maghrib', models.CharField(max_length=50)),
                ('isha', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PrayerTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('fajr_time', models.TimeField()),
                ('dhuhr_time', models.TimeField()),
                ('asr_time', models.TimeField()),
                ('maghrib_time', models.TimeField()),
                ('isha_time', models.TimeField()),
                ('mosque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.mosque')),
            ],
        ),
    ]
