# Generated by Django 4.2.5 on 2023-09-13 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prayertime',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
